export const PERMISSIONS = {
  // Gestión de usuarios
  CREATE_USERS: 'CREATE_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  DELETE_USERS: 'DELETE_USERS',
  VIEW_ALL_USERS: 'VIEW_ALL_USERS',
  
  // Gestión de pedidos
  VIEW_ALL_REQUESTS: 'VIEW_ALL_REQUESTS',
  APPROVE_REQUESTS: 'APPROVE_REQUESTS',
  CREATE_REQUESTS: 'CREATE_REQUESTS',
  AUDIT_REQUESTS: 'AUDIT_REQUESTS',
  
  // Gestión de cotizaciones y órdenes
  CREATE_QUOTATIONS: 'CREATE_QUOTATIONS',
  MANAGE_ORDERS: 'MANAGE_ORDERS',
  
  // Analytics y reportes
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  
  // Acceso administrativo
  ADMIN_ACCESS: 'ADMIN_ACCESS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS = {
  Administrador: [
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.UPDATE_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.VIEW_ALL_USERS,
    PERMISSIONS.VIEW_ALL_REQUESTS,
    PERMISSIONS.APPROVE_REQUESTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.ADMIN_ACCESS,
  ],
  Auditor: [
    PERMISSIONS.AUDIT_REQUESTS,
    PERMISSIONS.VIEW_ALL_REQUESTS,
    PERMISSIONS.APPROVE_REQUESTS,
    PERMISSIONS.VIEW_ALL_USERS,
  ],
  Efector: [
    PERMISSIONS.CREATE_REQUESTS,
  ],
  Proveedor: [
    PERMISSIONS.CREATE_QUOTATIONS,
    PERMISSIONS.MANAGE_ORDERS,
  ],
  Médico: [
    PERMISSIONS.CREATE_REQUESTS,
  ],
  Afiliado: [],
} as const; 